opcua:
  configuration:
    enabled: true
    name: akri-opcua
    capacity: 1
    discoveryDetails:
      # discoveryUrls is a list of DiscoveryUrls for OPC UA servers
      discoveryUrls:
        - "<OPC-UA server URL to scan for the below mentioned server>"
        - "<OPC-UA server URL to scan for the below mentioned server>"

      applicationNames:
        action: Include
        items: ["<OPC-UA server applicationName here>"]
    pod:
      restartPolicy: Always
      enabled: true
      volumes:
        - name: oisp-devices-config-volume
          configMap:
            name: <Name of the configmap that contains OISP device config>
            items:
              - key: config.json
                path: config.json
        - name: dataservice-machine-config
          configMap:
            name: <Name of the configmap that contains OPC-UA machine config>
            items:
              - key: config.json
                path: config.json
      imagePullSecrets:
        - name: regcred

    brokerPod1:
      name: fusionopcuadataservice
      image:
        repository: <fusion OPC-UA data service Docker image name>
        tag: <Version of the Docker image>
        pullPolicy: Always
      env: 
        OISP_URL: "127.0.0.1"
        OISP_PORT: "7070"
        OPC_USERNAME: ""
        OPC_PASSWORD: ""
        OISP_API_ROOT: "https://<PDT URL>/oisp/v1/api"
        USERNAME: "<Username of admin in PDT keycloak>"
        OISP_DEVICE_ID: "<Asset ID in PDT-Scorpio to which data must be sent>"
      envFrom:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: oisp-password-secret
      volumeMounts:
        - name: dataservice-machine-config
          mountPath: /resources/config.json
          subPath: config.json

    brokerPod2:
      name: oisp-iot-agent
      image:
        repository: <OISP agent Docker image name>
        tag: <OISP agent Docker image version>
        pullPolicy: Always
      env:
        OISP_DEVICE_ID: "<Asset ID in PDT-Scorpio to which data must be sent>"
        OISP_DEVICE_NAME: "<Asset ID in PDT-Scorpio to which data must be sent>"
        OISP_GATEWAY_ID: "<Asset ID in PDT-Scorpio to which data must be sent>"
      envFrom:
        - name: OISP_DEVICE_ACTIVATION_CODE
          valueFrom:
            secretKeyRef:
              key: activation-code
              name: <Name of the secret that contains OISP activation code>
      volumeMounts:
        - name: oisp-devices-config-volume
          mountPath: /volume/config
      securityContext:
        privileged: true
        capabilities:
          drop: ["ALL"]
      ports:
        - containerPort: 41234
          hostPort: 41234
        - containerPort: 7070
          hostPort: 7070

crds:
  group: akri.sh
  version: v0