apiVersion: apps/v1
kind: Deployment
metadata:
  name: oisp-operator-1
  labels:
    app: oisp-operator-1
spec:
  selector:
    matchLabels:
      app: oisp-operator-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oisp-operator-1
    spec:
      serviceAccountName: kopfexample-account
      restartPolicy: Always
      containers:
      - name: oisp-token-operator
        image: <Name of the OISP-token operator image>
        imagePullPolicy: Always
        env:
          - name: OISP_API_ROOT
            value: https://<PDT URL>/oisp/v1/api
          - name: USERNAME
            value: <Username of admin in PDT keycloak>
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oisp-password-secret
        securityContext:
          privileged: true
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kopfexample-account
  namespace: oisp-devices

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kopfexample-role
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kopfexample-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopfexample-role
subjects:
  - kind: ServiceAccount
    name: kopfexample-account
    namespace: oisp-devices

---

## The secret for pulling the Docker images. Create your own for your private repo.
apiVersion: v1
data:
  .dockerconfigjson: <encrypted Docker credentials here>
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: oisp-devices
type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
stringData:
  password: "<Password of the admin in PDT keycloak>"
kind: Secret
metadata:
  creationTimestamp: null
  name: oisp-password-secret
  namespace: oisp-devices

---